sudo: false
language: python
cache: pip

script:
  - tox

install:
  - pip install tox

matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27-django111-alchemy12-mongoengine015
    - python: "3.4"
      env: TOXENV=py34-django20-alchemy12-mongoengine015
    - python: "3.5"
      env: TOXENV=py35-django20-alchemy12-mongoengine015
    - python: "3.6"
      env: TOXENV=py36-django20-alchemy12-mongoengine015
    - python: "nightly"
      env: TOXENV=py37-django20-alchemy12-mongoengine015

    # Django LTS
    - python: "3.6"
      env: TOXENV=py36-django111-alchemy12-mongoengine015

    # Pypy
    - python: "pypy"
      env: TOXENV=pypy27-django111-alchemy12-mongoengine015
    - python: "pypy3"
      env: TOXENV=pypy3-django20-alchemy12-mongoengine015

    # Linting
    - python: "3.6"
      env: TOXENV=examples
    - python: "3.6"
      env: TOXENV=lint

services:
  - mongodb

notifications:
  email: false
  irc: "irc.freenode.org#factory_boy"
